// Code generated by generator, DO NOT EDIT.
package example

import gorpc "github.com/pongsatt/go-rpc"

// ServerProxy struct
type ServerProxy struct {
	client *gorpc.RequestReplyClient
}

// NewServerProxy creates new instance
func NewServerProxy(client *gorpc.RequestReplyClient) *ServerProxy {
	return &ServerProxy{client}
}

// Create func
func (proxy *ServerProxy) Create(order *Order) (string, error) {
	var f func(*Order) (string, error)
	gorpc.Call("Create", &f, func(reqBytes []byte) ([]byte, error) {
		return proxy.client.Request(order.ID, reqBytes)
	})
	return f(order)
}

// GetID func
func (proxy *ServerProxy) GetID(seed string) (string, error) {
	var f func(string) (string, error)
	gorpc.Call("GetID", &f, func(reqBytes []byte) ([]byte, error) {
		return proxy.client.Request("", reqBytes)
	})
	return f(seed)
}
