// Code generated by generator, DO NOT EDIT.
package example

import (
	"fmt"
	gorpc "github.com/pongsatt/go-rpc"
)

// NewRealServerProvider creates new instance
func NewRealServerProvider(client *gorpc.RequestReplyClient, realServer *RealServer) error {
	return client.SubscribeRequest(func(reqBytes []byte) ([]byte, error) {
		req, err := gorpc.Decode(reqBytes)
		if err != nil {
			return nil, err
		}
		switch req.Name {
		case "GetID":
			return gorpc.Execute(req, realServer.GetID)
		case "Create":
			return gorpc.Execute(req, realServer.Create)
		}
		return nil, fmt.Errorf("method '%s' is not supported", req.Name)
	})
}
